// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRUybmsbcQ50ONzDfu-8j_F3uMbqaqsXw',
    appId: '1:335006259919:web:7c120d12742e25f25a75ba',
    messagingSenderId: '335006259919',
    projectId: 'yugidex-7169d',
    authDomain: 'yugidex-7169d.firebaseapp.com',
    storageBucket: 'yugidex-7169d.appspot.com',
    measurementId: 'G-TQ3L31NTMX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCueRAoTDowJuUdgQ5n8T2IzwuqX_T4w8Y',
    appId: '1:335006259919:android:5917b4e5da98479c5a75ba',
    messagingSenderId: '335006259919',
    projectId: 'yugidex-7169d',
    storageBucket: 'yugidex-7169d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGvcBfy3E9FD85_50HtouC2ZwYVImfZ94',
    appId: '1:335006259919:ios:e90442d0122d4cb65a75ba',
    messagingSenderId: '335006259919',
    projectId: 'yugidex-7169d',
    storageBucket: 'yugidex-7169d.appspot.com',
    iosBundleId: 'com.example.yugiDex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGvcBfy3E9FD85_50HtouC2ZwYVImfZ94',
    appId: '1:335006259919:ios:3b17161726f95a1c5a75ba',
    messagingSenderId: '335006259919',
    projectId: 'yugidex-7169d',
    storageBucket: 'yugidex-7169d.appspot.com',
    iosBundleId: 'com.example.yugiDex.RunnerTests',
  );
}
